import Head from "next/head";
import requests from "../ultils/requests";
import FlipMove from "react-flip-move";
import { Thunbnail } from "../components/Thunbnail";
export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="row">
      <FlipMove className="my-10 px-5 sm:grid md:grid-cols-2 xl:grid-cols-3 3xl:flex flex-wrap justify-center">
      {results.results.map((res) => {
        return  <Thunbnail res={res} key={res.id} />
      })}
    </FlipMove>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const req = await fetch(
    `https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`).then((res) => res.json());
  return {
    props: {
      results: JSON.parse(JSON.stringify(req)),
    },
  };
}
